<article class="learning-reader">
    <header class="learning-reader-hero">
        <div><p class="learning-reader-kicker">Modul {{ $learningSession->module->module_number }} · Pertemuan {{ $learningSession->session_number }}</p><h1>{{ $learningSession->title }}</h1><p>{{ $learningSession->module->title }} · Semester {{ $learningSession->semester }} · {{ $learningSession->duration_minutes }} menit</p></div>
        <div class="learning-reader-orbit"><strong>{{ str_pad($learningSession->session_number, 2, '0', STR_PAD_LEFT) }}</strong><small>/ 30</small></div>
    </header>
    <section class="learning-reader-section"><p class="skuad-eyebrow">Tujuan pembelajaran</p><h2>Setelah pertemuan ini, kamu mampu</h2><ol class="learning-objectives">@foreach($learningSession->objectives as $objective)<li>{{ $objective }}</li>@endforeach</ol></section>
    @if($learningSession->introduction)<section class="learning-reader-section learning-prose"><p class="skuad-eyebrow">Pengantar & teori</p><h2>Pahami konsepnya</h2><p>{!! nl2br(e($learningSession->introduction)) !!}</p></section>@endif
    <section class="learning-reader-section"><p class="skuad-eyebrow">Materi</p><h2>Pelajari langkah demi langkah</h2><div class="learning-content-list">@forelse($learningSession->materials as $material)<article class="learning-content-item"><span class="learning-material-icon"><i class="bi {{ $material->type->icon() }}"></i></span><div><div class="d-flex flex-wrap gap-2 mb-2"><x-ui.badge>{{ $material->type->label() }}</x-ui.badge>@if($material->is_required)<x-ui.badge variant="warning">Wajib</x-ui.badge>@endif</div><h3>{{ $material->title }}</h3>@if($material->content)<p>{!! nl2br(e($material->content)) !!}</p>@endif @if($material->url)<a href="{{ $material->url }}" target="_blank" rel="noopener noreferrer">Buka materi <i class="bi bi-arrow-up-right"></i></a>@endif</div></article>@empty<div class="learning-module-empty">Belum ada materi pada pertemuan ini.</div>@endforelse</div></section>
    @if($learningSession->practice_instructions)<section class="learning-reader-section learning-practice"><p class="skuad-eyebrow">Latihan</p><h2>Saatnya mencoba</h2><p>{!! nl2br(e($learningSession->practice_instructions)) !!}</p></section>@endif
    @if($learningSession->summary)<section class="learning-reader-section learning-prose"><p class="skuad-eyebrow">Rangkuman</p><h2>Yang perlu diingat</h2><p>{!! nl2br(e($learningSession->summary)) !!}</p></section>@endif
    @if($learningSession->reflection_prompt)<section class="learning-reader-section learning-reflection"><p class="skuad-eyebrow">Refleksi</p><h2>Berhenti sejenak dan pikirkan</h2><blockquote>{{ $learningSession->reflection_prompt }}</blockquote></section>@endif
</article>
