<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="program_id">Program</label><select class="form-select @error('program_id') is-invalid @enderror" id="program_id" name="program_id" required><option value="">Pilih program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((int) old('program_id', $programBatch->program_id ?? 0) === $program->id)>{{ $program->name }}</option>@endforeach</select>@error('program_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="institution_id">Lembaga</label><select class="form-select @error('institution_id') is-invalid @enderror" id="institution_id" name="institution_id" required><option value="">Pilih lembaga</option>@foreach($institutions as $institution)<option value="{{ $institution->id }}" @selected((int) old('institution_id', $programBatch->institution_id ?? 0) === $institution->id)>{{ $institution->name }}</option>@endforeach</select>@error('institution_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="name">Nama batch/periode</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $programBatch->name ?? '') }}" placeholder="SKUAD SMPN 1 2026/2027" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $programBatch->slug ?? '') }}" placeholder="skuad-smpn-1-2026-2027">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="period_label">Periode/tahun ajaran</label><input class="form-control @error('period_label') is-invalid @enderror" id="period_label" name="period_label" value="{{ old('period_label', $programBatch->period_label ?? '') }}" placeholder="2026/2027 atau Batch 1" required>@error('period_label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="starts_on">Mulai</label><input class="form-control @error('starts_on') is-invalid @enderror" id="starts_on" name="starts_on" type="date" value="{{ old('starts_on', isset($programBatch) && $programBatch->starts_on ? $programBatch->starts_on->format('Y-m-d') : '') }}">@error('starts_on')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="ends_on">Selesai</label><input class="form-control @error('ends_on') is-invalid @enderror" id="ends_on" name="ends_on" type="date" value="{{ old('ends_on', isset($programBatch) && $programBatch->ends_on ? $programBatch->ends_on->format('Y-m-d') : '') }}">@error('ends_on')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="audience_type">Peruntukan</label><select class="form-select @error('audience_type') is-invalid @enderror" id="audience_type" name="audience_type" required>@foreach(['school' => 'Sekolah', 'community' => 'Komunitas', 'village' => 'Desa/RKDD', 'partner' => 'Mitra/Umum'] as $value => $label)<option value="{{ $value }}" @selected(old('audience_type', $programBatch->audience_type ?? 'school') === $value)>{{ $label }}</option>@endforeach</select>@error('audience_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="participant_label">Sebutan peserta</label><input class="form-control @error('participant_label') is-invalid @enderror" id="participant_label" name="participant_label" value="{{ old('participant_label', $programBatch->participant_label ?? 'Siswa') }}" placeholder="Siswa / Peserta / Peserta Didik" required>@error('participant_label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><input type="hidden" name="is_active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $programBatch->is_active ?? true))><label class="form-check-label fw-semibold" for="is_active">Batch/periode aktif</label></div>@error('is_active')<div class="text-danger small">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex justify-content-end gap-2 mt-4"><x-ui.button :href="route('super-admin.program-batches.index')" variant="ghost">Batal</x-ui.button><x-ui.button type="submit" icon="bi-check-lg">Simpan</x-ui.button></div>
