@php($model = $workType ?? null)
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="program_id">Program</label><select class="form-select @error('program_id') is-invalid @enderror" id="program_id" name="program_id" required><option value="">Pilih program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((int)old('program_id', $model->program_id ?? request('program_id')) === $program->id)>{{ $program->name }}</option>@endforeach</select>@error('program_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="name">Nama jenis karya</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $model->name ?? '') }}" placeholder="Contoh: Artikel berita" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $model->slug ?? '') }}" placeholder="artikel_berita">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Boleh dikosongkan, sistem akan membuat dari nama.</div></div>
    <div class="col-md-6"><label class="form-label" for="sort_order">Urutan</label><input class="form-control @error('sort_order') is-invalid @enderror" id="sort_order" name="sort_order" type="number" min="0" max="9999" value="{{ old('sort_order', $model->sort_order ?? 0) }}">@error('sort_order')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><input type="hidden" name="is_active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $model->is_active ?? true))><label class="form-check-label" for="is_active">Jenis karya aktif</label></div></div>
</div>
<div class="d-flex justify-content-end gap-2 mt-4"><x-ui.button :href="route('super-admin.portfolio-work-types.index')" variant="ghost">Batal</x-ui.button><x-ui.button type="submit">Simpan jenis karya</x-ui.button></div>
