@extends('layouts.dashboard')
@section('title','Dashboard Kepala Sekolah - RKDD')
@section('breadcrumb','Monitoring sekolah')
@section('content')
@php
    $principalProgramContext = app(\App\Services\ProgramContextService::class);
    $principalParticipantLabel = $principalProgramContext->participantLabel(auth()->user());
    $principalActiveBatch = $principalProgramContext->activeBatch(auth()->user());
    $attendanceMax=max(1,...array_values($attendance?:[0])); $gradeMax=max(1,...array_values($grades?:[0])); $logMax=max(1,...array_values($teacherLogs?:[0]));
@endphp
<div class="lead-dashboard-page principal-dashboard">
    <section class="lead-dashboard-hero principal-hero"><div><p>Executive overview</p><h1>Monitoring {{ $principalActiveBatch?->program?->name ?? 'program RKDD' }}.</h1><span>{{ $year?->name ?? 'Periode belum tersedia' }} · Ringkasan capaian yang dapat ditelusuri dari data operasional.</span></div><form method="GET"><label for="year">Periode</label><select class="form-select" id="year" name="year" onchange="this.form.submit()">@forelse($years as $option)<option value="{{ $option->id }}" @selected($year?->id===$option->id)>{{ $option->name }}{{ $option->is_active?' · Aktif':'' }}</option>@empty<option>Belum tersedia</option>@endforelse</select></form></section>
    <section class="principal-scoreboard"><article><small>Progress kurikulum</small><strong>{{ $summary['sessions'] }}<span>/{{ $summary['total_sessions'] ?? 0 }}</span></strong><p>Pertemuan selesai</p></article><article><small>Kehadiran {{ strtolower($principalParticipantLabel) }}</small><strong>{{ $summary['attendance'] }}<span>%</span></strong><p>Hadir dan terlambat</p></article><article><small>Rata-rata nilai</small><strong>{{ $summary['average_grade'] }}</strong><p>Nilai dipublikasikan</p></article><article><small>Absen terverifikasi</small><strong>{{ $summary['teacher_logs'] }}</strong><p>Catatan pengajar</p></article><article><small>Catatan terbuka</small><strong>{{ $summary['open_notes'] }}</strong><p>Memerlukan tindak lanjut</p></article><article><small>Dokumen aktif</small><strong>{{ $summary['documents'] }}</strong><p>Sumber daya periode</p></article></section>
    <section class="executive-chart-grid"><article class="lead-panel"><header><div><p class="skuad-eyebrow">Kehadiran</p><h2>Komposisi status</h2></div></header><div class="bar-chart">@foreach(\App\Enums\AttendanceStatus::cases() as $status)@php($value=(int)($attendance[$status->value]??0))<div><span>{{ $status->label() }}</span><i><b style="width:{{ $value/$attendanceMax*100 }}%"></b></i><strong>{{ $value }}</strong></div>@endforeach</div></article><article class="lead-panel"><header><div><p class="skuad-eyebrow">Penilaian</p><h2>Distribusi nilai</h2></div></header><div class="bar-chart chart-orange">@foreach($grades as $label=>$value)<div><span>{{ $label }}</span><i><b style="width:{{ $value/$gradeMax*100 }}%"></b></i><strong>{{ $value }}</strong></div>@endforeach</div></article><article class="lead-panel"><header><div><p class="skuad-eyebrow">Akuntabilitas</p><h2>Status absen pengajar</h2></div></header><div class="bar-chart chart-navy">@foreach($teacherLogs as $label=>$value)<div><span>{{ $label }}</span><i><b style="width:{{ $value/$logMax*100 }}%"></b></i><strong>{{ $value }}</strong></div>@endforeach</div></article></section>
    <div class="lead-dashboard-columns"><section class="lead-panel"><header><div><p class="skuad-eyebrow">Catatan program</p><h2>Catatan terbaru</h2></div></header><div class="compact-monitor-list">@forelse($notes as $note)<div class="monitor-static"><span class="priority-dot priority-{{ $note->priority->value }}"></span><div><strong>{{ Str::limit($note->note,85) }}</strong><small>{{ $note->note_date->translatedFormat('d M Y') }} · {{ $note->status->label() }}</small></div></div>@empty<div class="lead-empty"><p>Belum ada catatan program.</p></div>@endforelse</div></section><section class="lead-panel"><header><div><p class="skuad-eyebrow">Sumber daya</p><h2>Dokumen terbaru</h2></div><a href="{{ route('documents.index') }}">Buka pusat dokumen</a></header><div class="compact-monitor-list">@forelse($documents as $document)<a href="{{ route('documents.show',$document) }}"><span class="monitor-number"><i class="bi bi-file-earmark-text"></i></span><div><strong>{{ $document->title }}</strong><small>{{ $document->category->label() }} · {{ $document->published_at->diffForHumans() }}</small></div></a>@empty<div class="lead-empty"><p>Belum ada dokumen aktif.</p></div>@endforelse</div></section></div>
</div>
@endsection
