<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Nama lembaga</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $institution->name ?? '') }}" placeholder="SMP/MTs atau RKDD Cikampek Selatan" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $institution->slug ?? '') }}" placeholder="rkdd-cikampek-selatan">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="type">Tipe lembaga</label><select class="form-select @error('type') is-invalid @enderror" id="type" name="type" required>@foreach(['sekolah' => 'Sekolah', 'rkdd' => 'RKDD/Desa', 'komunitas' => 'Komunitas', 'organisasi' => 'Organisasi', 'mitra' => 'Mitra'] as $value => $label)<option value="{{ $value }}" @selected(old('type', $institution->type ?? 'sekolah') === $value)>{{ $label }}</option>@endforeach</select>@error('type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="address">Alamat/keterangan lokasi</label><input class="form-control @error('address') is-invalid @enderror" id="address" name="address" value="{{ old('address', $institution->address ?? '') }}" placeholder="Opsional">@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="description">Catatan lembaga</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="4">{{ old('description', $institution->description ?? '') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><input type="hidden" name="is_active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $institution->is_active ?? true))><label class="form-check-label fw-semibold" for="is_active">Lembaga aktif</label></div>@error('is_active')<div class="text-danger small">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex justify-content-end gap-2 mt-4"><x-ui.button :href="route('super-admin.institutions.index')" variant="ghost">Batal</x-ui.button><x-ui.button type="submit" icon="bi-check-lg">Simpan</x-ui.button></div>
