<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="academic_year_id">Tahun ajaran</label><select class="form-select @error('academic_year_id') is-invalid @enderror" id="academic_year_id" name="academic_year_id" required><option value="">Pilih tahun</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected((string) old('academic_year_id', $learningModule->academic_year_id ?? '') === (string) $year->id)>{{ $year->name }}</option>@endforeach</select>@error('academic_year_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="module_number">Nomor modul</label><input class="form-control @error('module_number') is-invalid @enderror" id="module_number" name="module_number" type="number" min="1" max="15" value="{{ old('module_number', $learningModule->module_number ?? '') }}" required>@error('module_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="sort_order">Urutan</label><input class="form-control" id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $learningModule->sort_order ?? 0) }}" required></div>
    <div class="col-12"><label class="form-label" for="title">Judul modul</label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $learningModule->title ?? '') }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="description">Deskripsi</label><textarea class="form-control" id="description" name="description" rows="4">{{ old('description', $learningModule->description ?? '') }}</textarea></div>
    <div class="col-12"><input type="hidden" name="is_active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $learningModule->is_active ?? true))><label class="form-check-label" for="is_active">Modul aktif</label></div></div>
</div>
<div class="d-flex justify-content-end gap-2 mt-4"><x-ui.button :href="route('teacher.learning.index')" variant="ghost">Batal</x-ui.button><x-ui.button type="submit" icon="bi-check-lg">Simpan modul</x-ui.button></div>
