@php($owner = $item->owner ?? $item->owner()->first())
<div class="portfolio-page">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <section class="portfolio-detail-hero">
        <div><p>{{ $item->workTypeLabel() }} · {{ $item->source_type === 'graded' ? 'Karya dinilai' : 'Karya mandiri' }}</p><h1>{{ $item->title }}</h1><span>Oleh {{ $owner?->name }}{{ $item->schoolClass ? ' · '.$item->schoolClass->name : '' }}</span><div class="portfolio-pills"><b>{{ $item->visibility->label() }}</b><b class="approval-{{ $item->approval_status->value }}">{{ $item->approval_status->label() }}</b>@if($item->is_featured)<b class="featured"><i class="bi bi-stars"></i> Featured</b>@endif</div></div>
        <div class="portfolio-detail-cover">@if($item->thumbnail_path)<img src="{{ route('portfolio.assets',[$item,'thumbnail']) }}" alt="Thumbnail {{ $item->title }}">@else<i class="bi bi-images"></i>@endif</div>
    </section>
    <div class="portfolio-detail-grid"><main class="portfolio-paper"><section><small>Tentang karya</small><p>{!! nl2br(e($item->description)) !!}</p></section><section><small>Refleksi proses</small><p>{!! nl2br(e($item->reflection ?: 'Belum ada refleksi.')) !!}</p></section><section><small>Sumber dan referensi</small><p>{!! nl2br(e($item->sources ?: 'Tidak ada sumber yang dicantumkan.')) !!}</p></section><section><small>Deklarasi AI</small><p>{{ $item->ai_used ? 'Menggunakan '.$item->ai_tools.'. '.$item->ai_usage_description : 'Karya ini dinyatakan tidak menggunakan bantuan AI.' }}</p></section>@if($item->submission?->grade)<section><small>Nilai dan feedback</small><div class="portfolio-grade"><strong>{{ number_format((float)$item->submission->grade->total_score,0) }}</strong><p>{{ $item->submission->grade->feedback ?: 'Belum ada feedback.' }}</p></div></section>@endif</main>
        <aside class="portfolio-side"><h2>Versi karya</h2><div class="portfolio-version"><span>Versi awal</span>@if($item->initial_file_path || $item->initialVersion?->files?->isNotEmpty())<a href="{{ route('portfolio.assets',[$item,'initial']) }}">Unduh file <i class="bi bi-download"></i></a>@elseif($item->initial_url)<a href="{{ $item->initial_url }}" target="_blank" rel="noopener">Buka tautan <i class="bi bi-box-arrow-up-right"></i></a>@else<em>Belum tersedia</em>@endif</div><div class="portfolio-version"><span>Versi final</span>@if($item->final_file_path || $item->finalVersion?->files?->isNotEmpty())<a href="{{ route('portfolio.assets',[$item,'final']) }}">Unduh file <i class="bi bi-download"></i></a>@elseif($item->final_url)<a href="{{ $item->final_url }}" target="_blank" rel="noopener">Buka tautan <i class="bi bi-box-arrow-up-right"></i></a>@else<em>Belum tersedia</em>@endif</div>
        @if($teacherMode)<div class="portfolio-review"><h2>Keputusan pembina</h2>@can('approve',$item)<form method="POST" action="{{ route('teacher.portfolio.review',$item) }}">@csrf @method('PATCH')<textarea class="form-control" name="approval_note" rows="3" placeholder="Catatan keputusan">{{ old('approval_note',$item->approval_note) }}</textarea><div><button class="btn btn-success" name="decision" value="approved">Setujui</button><button class="btn btn-outline-danger" name="decision" value="rejected">Tolak</button></div></form>@else<p>Karya ini tidak memerlukan approval.</p>@endcan @can('feature',$item)<form method="POST" action="{{ route('teacher.portfolio.feature',$item) }}">@csrf @method('PATCH')<button class="btn btn-outline-warning w-100"><i class="bi bi-stars"></i> {{ $item->is_featured ? 'Lepas featured' : 'Jadikan featured' }}</button></form>@endcan</div>@elseif(!$publicMode)<div class="portfolio-actions"><a class="btn btn-outline-primary" href="{{ route('student.portfolio.print',$item) }}" target="_blank"><i class="bi bi-printer"></i> Cetak</a><a class="btn btn-primary" href="{{ route('student.portfolio.edit',$item) }}"><i class="bi bi-pencil"></i> Edit</a><form method="POST" action="{{ route('student.portfolio.destroy',$item) }}" onsubmit="return confirm('Hapus karya ini?')">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100">Hapus</button></form></div>@endif
        </aside></div>
</div>
