@extends('layouts.dashboard')
@section('title',($announcement->exists?'Edit':'Buat').' Pengumuman - SKUAD')
@section('breadcrumb',$announcement->exists?'Edit pengumuman':'Buat pengumuman')
@section('content')
<div class="interaction-page"><section class="interaction-form-head"><p class="skuad-eyebrow">Pusat informasi</p><h1>{{ $announcement->exists ? 'Perbarui pengumuman' : 'Sampaikan informasi dengan jelas' }}</h1><span>Audience hanya menerima informasi yang relevan dengan perannya, kelasnya, atau pertemuannya.</span></section>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="interaction-form" method="POST" action="{{ $announcement->exists?route('teacher.announcements.update',$announcement):route('teacher.announcements.store') }}">@csrf @if($announcement->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-12"><label class="form-label">Judul</label><input class="form-control form-control-lg" name="title" value="{{ old('title',$announcement->title) }}" required></div><div class="col-12"><label class="form-label">Isi pengumuman</label><textarea class="form-control" name="body" rows="8" required>{{ old('body',$announcement->body) }}</textarea></div><div class="col-md-4"><label class="form-label">Audience</label><select class="form-select" name="audience">@foreach($audiences as $audience)<option value="{{ $audience->value }}" @selected(old('audience',$announcement->audience?->value)===$audience->value)>{{ $audience->label() }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Prioritas</label><select class="form-select" name="priority">@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority',$announcement->priority?->value)===$priority->value)>{{ $priority->label() }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Periode/Tahun Ajaran</label><select class="form-select" name="academic_year_id"><option value="">Tidak dibatasi</option>@foreach($years as $year)<option value="{{ $year->id }}" @selected((string)old('academic_year_id',$announcement->academic_year_id)===(string)$year->id)>{{ $year->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Kelompok/Angkatan</label><select class="form-select" name="class_id"><option value="">Pilih jika audience kelompok</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected((string)old('class_id',$announcement->class_id)===(string)$class->id)>{{ $class->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Pertemuan</label><select class="form-select" name="learning_session_id"><option value="">Pilih jika audience pertemuan</option>@foreach($sessions as $session)<option value="{{ $session->id }}" @selected((string)old('learning_session_id',$announcement->learning_session_id)===(string)$session->id)>P{{ $session->session_number }} · {{ $session->title }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Waktu publikasi</label><input class="form-control" type="datetime-local" name="published_at" value="{{ old('published_at',$announcement->published_at?->format('Y-m-d\TH:i')) }}"></div><div class="col-md-6"><label class="form-label">Kedaluwarsa</label><input class="form-control" type="datetime-local" name="expires_at" value="{{ old('expires_at',$announcement->expires_at?->format('Y-m-d\TH:i')) }}"></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_pinned" value="1" id="is_pinned" @checked(old('is_pinned',$announcement->is_pinned))><label class="form-check-label" for="is_pinned">Sematkan di urutan teratas</label></div></div></div>
<div class="interaction-sticky"><a class="btn btn-light" href="{{ route('interactions.announcements.index') }}">Batal</a><button class="btn btn-outline-primary" name="action" value="draft">Simpan draf</button><button class="btn btn-primary" name="action" value="publish">Publikasikan</button></div></form></div>
@endsection
