@extends('layouts.dashboard')
@section('title', 'Kurasi Portofolio - SKUAD')
@section('breadcrumb', 'Kurasi portofolio')
@section('content')
<div class="portfolio-page">
    <section class="portfolio-hero portfolio-hero-teacher"><div><p>Ruang kurasi pembina</p><h1>Temukan karya yang layak bersinar.</h1><span>Tinjau konteks, proses, deklarasi AI, dan visibilitas sebelum memberi persetujuan.</span></div><strong>{{ $items->total() }} karya</strong></section>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <form class="portfolio-filter" method="GET"><input class="form-control" name="q" value="{{ $filters['q']??'' }}" placeholder="Cari karya atau siswa"><select class="form-select" name="work_type"><option value="">Semua jenis</option>@foreach($workTypes as $type)<option value="{{ $type->slug }}" @selected(($filters['work_type']??'')===$type->slug)>{{ $type->name }}</option>@endforeach</select><select class="form-select" name="visibility"><option value="">Semua akses</option>@foreach($visibilities as $visibility)<option value="{{ $visibility->value }}" @selected(($filters['visibility']??'')===$visibility->value)>{{ $visibility->label() }}</option>@endforeach</select><select class="form-select" name="approval_status"><option value="">Semua status</option>@foreach($approvalStatuses as $status)<option value="{{ $status->value }}" @selected(($filters['approval_status']??'')===$status->value)>{{ $status->label() }}</option>@endforeach</select><button class="btn btn-primary">Filter</button></form>
    <div class="portfolio-grid">@forelse($items as $item)<a class="portfolio-card" href="{{ route('teacher.portfolio.show',$item) }}"><div class="portfolio-thumb">@if($item->thumbnail_path)<img src="{{ route('portfolio.assets',[$item,'thumbnail']) }}" alt="">@else<i class="bi bi-palette2"></i>@endif @if($item->is_featured)<b><i class="bi bi-stars"></i> Featured</b>@endif</div><div class="portfolio-card-copy"><small>{{ $item->owner->name }} · {{ $item->schoolClass->name }}</small><h2>{{ $item->title }}</h2><p>{{ Str::limit($item->description,100) }}</p><div><span>{{ $item->visibility->label() }}</span><strong class="approval-{{ $item->approval_status->value }}">{{ $item->approval_status->label() }}</strong></div></div></a>@empty<div class="portfolio-empty"><i class="bi bi-search"></i><h2>Tidak ada karya</h2><p>Ubah filter untuk melihat hasil lain.</p></div>@endforelse</div>{{ $items->links() }}
</div>
@endsection
