@php($editing = isset($learningSession))
@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <strong>Pertemuan belum dapat disimpan.</strong>
        <ul class="mb-0 mt-2 ps-3">
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="academic_year_id">Tahun ajaran</label><select class="form-select @error('academic_year_id') is-invalid @enderror" id="academic_year_id" name="academic_year_id" required><option value="">Pilih tahun</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected((string) old('academic_year_id', $learningSession->academic_year_id ?? request('academic_year_id')) === (string) $year->id)>{{ $year->name }}</option>@endforeach</select>@error('academic_year_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="learning_module_id">Modul</label><select class="form-select @error('learning_module_id') is-invalid @enderror" id="learning_module_id" name="learning_module_id" required><option value="">Pilih modul</option>@foreach($modules as $module)<option value="{{ $module->id }}" @selected((string) old('learning_module_id', $learningSession->learning_module_id ?? request('module')) === (string) $module->id)>Modul {{ $module->module_number }} · {{ $module->title }} ({{ $module->academicYear->name }})</option>@endforeach</select>@error('learning_module_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="session_number">Nomor pertemuan</label><input class="form-control @error('session_number') is-invalid @enderror" id="session_number" name="session_number" type="number" min="1" max="255" value="{{ old('session_number', $learningSession->session_number ?? '') }}" required>@error('session_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="title">Judul pertemuan</label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $learningSession->title ?? '') }}" placeholder="Tulis judul sesuai rencana guru" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="duration_minutes">Durasi</label><div class="input-group"><input class="form-control @error('duration_minutes') is-invalid @enderror" id="duration_minutes" name="duration_minutes" type="number" min="30" max="240" value="{{ old('duration_minutes', $learningSession->duration_minutes ?? 90) }}"><span class="input-group-text">menit</span>@error('duration_minutes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status">@foreach(\App\Enums\LearningSessionStatus::cases() as $status) @if($status !== \App\Enums\LearningSessionStatus::Published || ($learningSession->status ?? null) === \App\Enums\LearningSessionStatus::Published)<option value="{{ $status->value }}" @selected(old('status', ($learningSession->status ?? \App\Enums\LearningSessionStatus::Draft)->value) === $status->value)>{{ $status->label() }}</option>@endif @endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="scheduled_at">Jadwal publikasi</label><input class="form-control @error('scheduled_at') is-invalid @enderror" id="scheduled_at" name="scheduled_at" type="datetime-local" value="{{ old('scheduled_at', isset($learningSession) && $learningSession->scheduled_at ? $learningSession->scheduled_at->format('Y-m-d\TH:i') : '') }}">@error('scheduled_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="objectives_text">Tujuan pembelajaran <small class="text-secondary">(satu per baris)</small></label><textarea class="form-control @error('objectives') is-invalid @enderror" id="objectives_text" name="objectives_text" rows="4" required>{{ old('objectives_text', isset($learningSession) ? implode("\n", $learningSession->objectives) : '') }}</textarea>@error('objectives')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="introduction">Pengantar dan teori</label><textarea class="form-control" id="introduction" name="introduction" rows="6">{{ old('introduction', $learningSession->introduction ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label" for="summary">Rangkuman</label><textarea class="form-control" id="summary" name="summary" rows="4">{{ old('summary', $learningSession->summary ?? '') }}</textarea></div>
    <div class="col-md-7"><label class="form-label" for="practice_instructions">Latihan</label><textarea class="form-control" id="practice_instructions" name="practice_instructions" rows="5">{{ old('practice_instructions', $learningSession->practice_instructions ?? '') }}</textarea></div>
    <div class="col-md-5"><label class="form-label" for="reflection_prompt">Pertanyaan refleksi</label><textarea class="form-control" id="reflection_prompt" name="reflection_prompt" rows="5">{{ old('reflection_prompt', $learningSession->reflection_prompt ?? '') }}</textarea></div>
</div>
<div class="d-flex flex-wrap justify-content-end gap-2 mt-4"><x-ui.button :href="route('teacher.learning.index')" variant="ghost">Kembali</x-ui.button>@if($editing)<x-ui.button :href="route('teacher.learning.sessions.preview', $learningSession)" variant="outline" icon="bi-eye">Preview</x-ui.button>@endif<x-ui.button type="submit" icon="bi-check-lg">Simpan pertemuan</x-ui.button></div>
