@extends('layouts.dashboard')
@section('title', 'Kelola Pertemuan') @section('breadcrumb', 'Kelola Pertemuan')
@section('content')
<x-ui.page-header eyebrow="Pertemuan {{ $learningSession->session_number }}" :title="$learningSession->title" :description="'Semester '.$learningSession->semester.' · '.$learningSession->duration_minutes.' menit'"><x-slot:actions>@unless($learningSession->status->isVisibleToStudents())<form method="POST" action="{{ route('teacher.learning.sessions.publish', $learningSession) }}" data-confirm="Publikasikan pertemuan ini?">@csrf @method('PATCH')<x-ui.button type="submit" icon="bi-send">Publish</x-ui.button></form>@endunless</x-slot:actions></x-ui.page-header>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @error('learning_session')<div class="alert alert-danger">{{ $message }}</div>@enderror
<div class="skuad-card p-4 p-lg-5 mb-4"><form method="POST" action="{{ route('teacher.learning.sessions.update', $learningSession) }}">@csrf @method('PUT') @include('teacher.learning.sessions._form')</form></div>
<section class="learning-material-manager"><div class="student-section-heading"><div><p class="skuad-eyebrow">Materi pertemuan</p><h2>Susun materi</h2></div><x-ui.badge>{{ $learningSession->materials->count() }} item</x-ui.badge></div>
<div class="learning-material-list">@forelse($learningSession->materials as $material)<article><span class="learning-material-icon"><i class="bi {{ $material->type->icon() }}"></i></span><div><strong>{{ $material->title }}</strong><small>{{ $material->type->label() }} · Urutan {{ $material->sort_order }}{{ $material->is_required ? ' · Wajib' : '' }}</small></div><div class="d-flex"><a class="skuad-icon-button" href="{{ route('teacher.learning.materials.edit', $material) }}" aria-label="Edit materi"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('teacher.learning.materials.destroy', $material) }}" data-confirm="Hapus materi ini?">@csrf @method('DELETE')<button class="skuad-icon-button text-danger" aria-label="Hapus materi"><i class="bi bi-trash"></i></button></form></div></article>@empty<div class="learning-module-empty">Belum ada materi. Tambahkan minimal satu sebelum publish.</div>@endforelse</div>
<form class="learning-material-form" method="POST" action="{{ route('teacher.learning.materials.store', $learningSession) }}">@csrf <h3>Tambah materi</h3>@include('teacher.learning.materials._form', ['learningMaterial' => null])</form></section>
@if(in_array($learningSession->status, [\App\Enums\LearningSessionStatus::Draft, \App\Enums\LearningSessionStatus::Scheduled, \App\Enums\LearningSessionStatus::Archived], true) && $learningSession->progress_records_count === 0)
<form class="mt-4" method="POST" action="{{ route('teacher.learning.sessions.destroy', $learningSession) }}" data-confirm="Hapus pertemuan ini dari kurikulum? Nomornya dapat digunakan kembali.">@csrf @method('DELETE')<x-ui.button type="submit" variant="ghost" icon="bi-trash">Hapus pertemuan</x-ui.button></form>
@else
<div class="alert alert-light border mt-4 mb-0">Pertemuan yang sedang dipublikasikan atau sudah memiliki progress siswa tidak dapat langsung dihapus. Ubah status menjadi arsip terlebih dahulu tanpa menghapus histori progress.</div>
@endif
@endsection
